// The vendored Lucide icon registry. Each name maps 1:1 to a verbatim SVG at
// ui/src/icons/<name>.svg (EXC-395); icons.test.ts enforces the bijection and
// per-file invariants. Adding an icon: see doc/agents/icon-rules.md.
export const ICON_NAMES = [
  "arrow-big-up",
  "bell",
  "bell-off",
  "check",
  "chevron-down",
  "chevron-right",
  "chevron-up",
  "circle-question-mark",
  "command",
  "copy",
  "corner-down-left",
  "corner-up-left",
  "ellipsis",
  "file",
  "folder",
  "git-compare",
  "heading-1",
  "heading-2",
  "heading-3",
  "heading-4",
  "heading-5",
  "heading-6",
  "keyboard",
  "loader-circle",
  "monitor",
  "moon",
  "panel-left",
  "refresh-cw",
  "search",
  "settings",
  "square",
  "square-check-big",
  "square-slash",
  "sun",
  "trash-2",
  "unplug",
  "x",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
