#!/usr/bin/env bun
// Generates the embed manifest the compiled binary serves the UI from (EXC-522):
// a module of static `with { type: "file" }` imports — one per file under
// ui/dist/ — plus a Record mapping each asset's request URL path to the import's
// resolved value. `bun build --compile` embeds the file imports into the binary
// (the resolved value becomes a /$bunfs path that survives source deletion);
// the daemon reads each through Bun.file, which also yields its MIME type. The
// output module is gitignored, biome-excluded, and runs inline from the build-bin
// task (scripts/build/build-bin.ts) after the UI is built and before the compile.
//
// Split into a pure renderer (renderManifestModule — unit-tested) and the
// filesystem effects (enumerateDist, writeManifest) so the URL mapping and the
// emitted module shape are verifiable without a real build.

import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

/** One asset: its request URL path, the import specifier (relative to the
 * generated module), and the JS identifier the import binds to. */
export interface ManifestEntry {
  /** The path a browser requests, e.g. "/index.html" or "/assets/index-AB12.js". */
  urlPath: string;
  /** The module specifier for the `with { type: "file" }` import, relative to
   * the generated module's location. */
  importPath: string;
  /** A safe JS identifier for the import binding. */
  varName: string;
}

/** Render the generated module's source from a set of entries. Pure: the same
 * entries always yield the same text, so the emitted module is reproducible. */
export function renderManifestModule(entries: ManifestEntry[]): string {
  const imports = entries
    .map((e) => `import ${e.varName} from "${e.importPath}" with { type: "file" };`)
    .join("\n");
  // String() narrows each binding to string and is identity at runtime: the
  // `with { type: "file" }` value is always the embedded path string, even where
  // @types/bun mistypes it by extension (e.g. .html as HTMLBundle).
  const records = entries
    .map((e) => `  ${JSON.stringify(e.urlPath)}: String(${e.varName}),`)
    .join("\n");
  return `// GENERATED by scripts/generate-ui-manifest.ts — do not edit.
// Maps each built UI asset's request URL path to its embedded file path. The
// \`with { type: "file" }\` imports embed the bytes into the compiled binary;
// the value is the embedded path string at runtime (see ui-manifest-assets.d.ts
// and the String() narrowing). EXC-522.
${imports}

export const UI_MANIFEST: Record<string, string> = {
${records}
};
`;
}

/** Build a stable JS identifier from a URL path (e.g. "/assets/index-AB12.js"
 * → "asset_assets_index_AB12_js"), prefixed so it never starts with a digit. */
function varNameFor(urlPath: string): string {
  return `asset_${urlPath.replace(/[^A-Za-z0-9]/g, "_")}`;
}

/** Enumerate every file under `distDir`, returning manifest entries sorted by
 * URL path (so the emitted module is order-stable across runs). `importPath` is
 * relative to `outFile`'s directory; `urlPath` is the dist-relative path with a
 * leading slash. */
export function enumerateDist(distDir: string, outFile: string): ManifestEntry[] {
  const files: string[] = [];
  const walk = (dir: string) => {
    for (const ent of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, ent.name);
      if (ent.isDirectory()) walk(full);
      else if (ent.isFile()) files.push(full);
    }
  };
  walk(distDir);

  const outDir = dirname(outFile);
  return files
    .map((full) => {
      const urlPath = `/${relative(distDir, full).split("\\").join("/")}`;
      let importPath = relative(outDir, full).split("\\").join("/");
      if (!importPath.startsWith(".")) importPath = `./${importPath}`;
      return { urlPath, importPath, varName: varNameFor(urlPath) };
    })
    .sort((a, b) => (a.urlPath < b.urlPath ? -1 : a.urlPath > b.urlPath ? 1 : 0));
}

/** Enumerate ui/dist/ and write the generated manifest module. Returns the
 * count of embedded assets. Throws if the dist tree is missing (the build task
 * runs build-ui first, so absence is a real error worth failing the build). */
export function writeManifest(distDir: string, outFile: string): number {
  const entries = enumerateDist(distDir, outFile);
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, renderManifestModule(entries));
  return entries.length;
}

if (import.meta.main) {
  const root = fileURLToPath(new URL("..", import.meta.url));
  const distDir = join(root, "ui", "dist");
  const outFile = join(root, "src", "ui-manifest.generated.ts");
  const count = writeManifest(distDir, outFile);
  process.stderr.write(`generated ${outFile} (${count} assets)\n`);
}
