#!/usr/bin/env bash
#
# Generate a private "dev" plugin marketplace pointing at a local caret checkout
# (EXC-643). The committed .claude-plugin/marketplace.json uses an npm source so
# the public `/plugin marketplace add macintacos/caret` installs the published
# package. A LOCAL build (scripts/install.sh, `mise run build --install`) must
# install THIS checkout instead, so it registers the marketplace this script
# writes: a throwaway directory whose single plugin's source ("./caret") is a
# symlink to the checkout. Claude Code copies the symlink-resolved tree — the
# freshly built bin/caret-native + bin/ui (and dist/ + ui/dist when present) —
# into its plugin cache, so the bin/caret shim execs the local build.
#
#   make-dev-marketplace.sh <repo-dir> <out-dir>
#
# Routed through install.sh's run() so a CARET_DRY_RUN preview records this as a
# single planned command and never actually writes anything.

set -euo pipefail

# Resolve repo_dir to an absolute path so the symlink below works regardless of
# the caller's cwd (a relative symlink target would dangle from out_dir).
repo_dir="$(cd "$1" && pwd)"
out_dir="$2"

rm -rf "$out_dir"
mkdir -p "$out_dir/.claude-plugin"
# Symlink rather than copy: the source is resolved at install time, so the
# marketplace always points at the latest build without re-running this script.
ln -s "$repo_dir" "$out_dir/caret"
cat >"$out_dir/.claude-plugin/marketplace.json" <<'JSON'
{
  "name": "caret",
  "description": "Local caret dev build (generated by scripts/make-dev-marketplace.sh).",
  "owner": { "name": "macintacos" },
  "plugins": [
    {
      "name": "caret",
      "source": "./caret",
      "description": "Local caret dev build."
    }
  ]
}
JSON
