#!/usr/bin/env bun
// Emits app.css's static first-paint palette from THEMES["caret-dark"] (EXC-886),
// so the caret-dark fallback exists in exactly one place. The output partial is
// gitignored, and every task that consumes app.css regenerates it first: the vite
// plugin in vite.config.ts (build + dev server, hence `test e2e`), plus `test
// unit`, `lint`, `format`, and `setup`. The one path that does NOT is hk invoked
// directly by the git pre-commit hook, whose Tailwind step loads app.css as its
// theme — it needs the partial to already exist, which any of those tasks
// provides.
//
// It lives at the ui/ root rather than under scripts/ because its module graph
// resolves $lib, an alias only ui/tsconfig.json carries — a root-program script
// importing it would be dragged into `tsc --noEmit`'s program with $lib unmapped.
//
// Split into a pure renderer (renderPaletteCss — unit-tested) and the filesystem
// effects (writePaletteCss), following scripts/generate-ui-manifest.ts.

import { renameSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { THEMES, type Theme } from "$lib/theme.ts";

/** The gitignored partial app.css @imports for its first-paint palette. */
export const PALETTE_CSS = fileURLToPath(
  new URL("./src/styles/palette.generated.css", import.meta.url),
);

/** Render a theme's palette as the static :root fallback. Pure: the same theme
 * always yields the same text, so the emitted partial is reproducible. */
export function renderPaletteCss(theme: Theme): string {
  const declarations = Object.entries(theme.tokens)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
  return `/* GENERATED by ui/generate-palette-css.ts — do not edit.
   ${theme.id}'s palette as the static first-paint / no-JS fallback (EXC-730),
   emitted from THEMES["${theme.id}"] in lib/theme.ts — the source of truth,
   whose paintTheme() writes these same tokens (and every other palette's) as
   inline custom properties to switch palettes at runtime. Which palette is live
   is decided by lib/appearance.ts — a light/dark/system mode over one theme slot
   per scheme (EXC-773) — so the UI follows prefers-color-scheme by default,
   through that resolution rather than a CSS media query. This block is the
   pre-JS floor either way. */
:root {
${declarations}
  color-scheme: ${theme.scheme};
}
`;
}

/** Write the partial atomically — the preflight gate runs `lint`, `test`, and
 * `build ui` concurrently, and each regenerates it. The temp name carries the
 * pid so concurrent writers can't collide, and POSIX rename is atomic, so a
 * reader sees either the old file or the new one, never a torn one.
 *
 * @param out - Where to write. Defaults to the production partial; tests pass a
 * temp path so the rename is exercisable without clobbering the real artifact. */
export function writePaletteCss(out: string = PALETTE_CSS): void {
  const tmp = `${out}.${process.pid}.tmp`;
  writeFileSync(tmp, renderPaletteCss(THEMES["caret-dark"]));
  renameSync(tmp, out);
}

if (import.meta.main) writePaletteCss();
