#!/usr/bin/env bun
// Emits app.css's static first-paint palette from THEMES["caret-dark"] (EXC-886),
// so the caret-dark fallback exists in exactly one place. The output partial is
// gitignored and regenerated by every path that consumes app.css: the vite plugin
// in vite.config.ts (build + dev server), `test unit`, and `setup`.
//
// It lives at the ui/ root rather than under scripts/ because its module graph
// resolves $lib, an alias only ui/tsconfig.json carries — a root-program script
// importing it would be dragged into `tsc --noEmit`'s program with $lib unmapped.
//
// Split into a pure renderer (renderPaletteCss — unit-tested) and the filesystem
// effects (writePaletteCss), following scripts/generate-ui-manifest.ts.

import { renameSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { THEMES, type Theme } from "$lib/theme.ts";

/** The gitignored partial app.css @imports for its first-paint palette. */
export const PALETTE_CSS = fileURLToPath(
  new URL("./src/styles/palette.generated.css", import.meta.url),
);

/** Render a theme's palette as the static :root fallback. Pure: the same theme
 * always yields the same text, so the emitted partial is reproducible. */
export function renderPaletteCss(theme: Theme): string {
  const declarations = Object.entries(theme.tokens)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
  return `/* GENERATED by ui/generate-palette-css.ts — do not edit.
   ${theme.id}'s palette as the static first-paint / no-JS fallback (EXC-730),
   emitted from THEMES["${theme.id}"] in lib/theme.ts — the source of truth,
   whose paintTheme() writes these same tokens (and every other palette's) as
   inline custom properties to switch palettes at runtime. Which palette is live
   is decided by lib/appearance.ts — a light/dark/system mode over one theme slot
   per scheme (EXC-773) — so the UI follows prefers-color-scheme by default,
   through that resolution rather than a CSS media query. This block is the
   pre-JS floor either way. */
:root {
${declarations}
  color-scheme: ${theme.scheme};
}
`;
}

/** Write the partial atomically — the preflight gate runs `test` and `build ui`
 * concurrently, and both regenerate it. POSIX rename is atomic, so a concurrent
 * reader sees either the old file or the new one, never a torn one. */
export function writePaletteCss(): void {
  const tmp = `${PALETTE_CSS}.${process.pid}.tmp`;
  writeFileSync(tmp, renderPaletteCss(THEMES["caret-dark"]));
  renameSync(tmp, PALETTE_CSS);
}

if (import.meta.main) writePaletteCss();
