// Pins the palette renderer: what it emits is app.css's static first-paint
// fallback, so it must carry every color token a Theme declares, the theme's
// color-scheme, and one flat :root block the CSS-contract suites can parse. The
// filesystem effects follow scripts/generate-ui-manifest.ts in staying untested
// — the emitted text is where a slip would live.
import { describe, expect, test } from "bun:test";

import { THEMES } from "$lib/theme.ts";

import { renderPaletteCss } from "./generate-palette-css.ts";

/** The emitted text with CSS comments stripped, so header prose can never be
 * mistaken for a declaration. */
function withoutComments(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, "");
}

describe("renderPaletteCss", () => {
  test("declares every color token the theme carries", () => {
    const css = renderPaletteCss(THEMES["caret-dark"]);
    for (const [name, value] of Object.entries(THEMES["caret-dark"].tokens)) {
      expect(css, name).toContain(`  ${name}: ${value};`);
    }
  });

  test("declares the theme's color-scheme", () => {
    expect(renderPaletteCss(THEMES["caret-dark"])).toContain("  color-scheme: dark;");
    expect(renderPaletteCss(THEMES["caret-light"])).toContain("  color-scheme: light;");
  });

  // The contract suites parse the flat sheet with a `[^}]*` body capture, which
  // yields the whole block only while nothing nested opens a brace.
  test("emits exactly one flat :root block", () => {
    const css = withoutComments(renderPaletteCss(THEMES["caret-dark"]));
    expect(css.match(/:root/g)).toHaveLength(1);
    const body = css.match(/:root\s*\{([^}]*)\}/)?.[1];
    expect(body).toBeDefined();
    expect(body).toContain("--shadow-card:");
    expect(body).toContain("color-scheme:");
  });

  test("names its generator in a do-not-edit header", () => {
    expect(renderPaletteCss(THEMES["caret-dark"])).toContain(
      "GENERATED by ui/generate-palette-css.ts — do not edit",
    );
  });

  test("renders deterministically", () => {
    expect(renderPaletteCss(THEMES["caret-dark"])).toBe(renderPaletteCss(THEMES["caret-dark"]));
  });
});
