// Pins the palette generator: what it emits is app.css's static first-paint
// fallback, so it must carry every color token a Theme declares, the theme's
// color-scheme, and one flat :root block the CSS-contract suites can parse — and
// app.css must actually import it, which nothing else in the repo checks now
// that the mirror test is gone.
import { describe, expect, test } from "bun:test";
import { existsSync, mkdtempSync, readdirSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { readAppCss } from "$lib/appCss.ts";
import { THEMES } from "$lib/theme.ts";

import { renderPaletteCss, writePaletteCss } from "./generate-palette-css.ts";

/** The emitted text with CSS comments stripped, so header prose can never be
 * mistaken for a declaration. */
function withoutComments(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, "");
}

describe("renderPaletteCss", () => {
  test("declares every color token the theme carries", () => {
    const css = renderPaletteCss(THEMES["caret-dark"]);
    for (const [name, value] of Object.entries(THEMES["caret-dark"].tokens)) {
      expect(css, name).toContain(`  ${name}: ${value};`);
    }
  });

  test("declares the theme's color-scheme", () => {
    expect(renderPaletteCss(THEMES["caret-dark"])).toContain("  color-scheme: dark;");
    expect(renderPaletteCss(THEMES["caret-light"])).toContain("  color-scheme: light;");
  });

  // The contract suites parse the flat sheet with a `[^}]*` body capture, which
  // yields the whole block only while nothing nested opens a brace.
  test("emits exactly one flat :root block", () => {
    const css = withoutComments(renderPaletteCss(THEMES["caret-dark"]));
    expect(css.match(/:root/g)).toHaveLength(1);
    const body = css.match(/:root\s*\{([^}]*)\}/)?.[1];
    expect(body).toBeDefined();
    expect(body).toContain("--shadow-card:");
    expect(body).toContain("color-scheme:");
  });

  test("names its generator in a do-not-edit header", () => {
    expect(renderPaletteCss(THEMES["caret-dark"])).toContain(
      "GENERATED by ui/generate-palette-css.ts — do not edit",
    );
  });

  test("renders deterministically", () => {
    expect(renderPaletteCss(THEMES["caret-dark"])).toBe(renderPaletteCss(THEMES["caret-dark"]));
  });
});

// The partial only reaches the browser because app.css @imports it, and that one
// line is now the whole first-paint fallback: delete it and the unit suite,
// svelte-check, and `vite build` all stay green while the no-JS floor is gone.
// Nothing else pins the wiring — the five other contract suites assert token
// *references*, and every e2e run has JS enabled, where paintTheme writes the
// palette inline regardless.
describe("app.css wiring", () => {
  test("the reconstituted sheet carries the emitted palette", () => {
    expect(readAppCss()).toContain(renderPaletteCss(THEMES["caret-dark"]));
  });
});

// The write is the file's one piece of non-obvious logic — a pid-suffixed temp
// renamed over the target, so the concurrent regenerations `lint`, `test`, and
// `build ui` perform under preflight can never expose a torn file. Driven into a
// temp dir through the injected path, so it never touches the real artifact.
describe("writePaletteCss", () => {
  test("writes the rendered palette and leaves no temp file behind", () => {
    const dir = mkdtempSync(join(tmpdir(), "caret-palette-"));
    const out = join(dir, "palette.generated.css");

    writePaletteCss(out);

    expect(readFileSync(out, "utf8")).toBe(renderPaletteCss(THEMES["caret-dark"]));
    expect(readdirSync(dir)).toEqual(["palette.generated.css"]);
    expect(existsSync(`${out}.${process.pid}.tmp`)).toBe(false);
  });

  test("overwrites an existing target", () => {
    const dir = mkdtempSync(join(tmpdir(), "caret-palette-"));
    const out = join(dir, "palette.generated.css");

    writePaletteCss(out);
    writePaletteCss(out);

    expect(readFileSync(out, "utf8")).toBe(renderPaletteCss(THEMES["caret-dark"]));
    expect(readdirSync(dir)).toEqual(["palette.generated.css"]);
  });
});
